databases:
  - name: postgresql
    databaseName: gt_backend
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        # value: "postgres://mysite:zMyr5PA3qKVvEDi7uSJntgdlKkMHkJo1@dpg-cn6bnfun7f5s73el8o6g-a.oregon-postgres.render.com/gt_backend"
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default